"""WordPress-core detection and default exclusion rules, consumed by
`/smith-index --init-system-paths` (scripts/smith-index/run.py). Pure,
stdlib-only, no filesystem writes — callers own all I/O. See BANK-028
for origin: WP-core files (wp-admin/, wp-includes/) dominate a stub
generated by the plain per-top-level-directory heuristic with zero
signal for the project's own site code.
"""

from __future__ import annotations
from pathlib import Path

# Directory-shaped WP-core exclusions. Trailing "/" matches this
# codebase's existing `system-paths.json` `prefix` convention for a
# directory rule (see e.g. skills/smith-index/templates/
# system-paths.json.example).
WP_CORE_DIRS: tuple[str, ...] = ("wp-admin/", "wp-includes/")

# Root-level WP-core files. Each is its OWN exact-match prefix — NEVER
# collapse these into a bare "wp-" prefix, which would also match
# wp-content/ (themes/plugins/uploads — the actual site code a
# WordPress project's owner cares about indexing). This is BANK-028's
# explicit, load-bearing gotcha.
WP_CORE_ROOT_FILES: tuple[str, ...] = (
    "index.php",
    "wp-activate.php",
    "wp-blog-header.php",
    "wp-comments-post.php",
    "wp-config-sample.php",
    "wp-config.php",
    "wp-cron.php",
    "wp-links-opml.php",
    "wp-load.php",
    "wp-login.php",
    "wp-mail.php",
    "wp-settings.php",
    "wp-signup.php",
    "wp-trackback.php",
    "xmlrpc.php",
)


def detect_wordpress(project_root: Path) -> bool:
    """True iff `project_root` looks like a WordPress-core checkout.

    Both `wp-load.php` (file) AND `wp-includes/` (directory) must be
    present — either alone is too weak a signal (a project vendoring one
    WP-flavored file, or an unrelated directory happening to be named
    `wp-includes`, must not trip auto-exclusion).
    """
    return (project_root / "wp-load.php").is_file() and (
        project_root / "wp-includes"
    ).is_dir()


def wp_exclusion_rules() -> list[dict]:
    """Return the 17 stub `rules` entries covering WordPress core.

    2 directory prefixes + 15 exact root-file prefixes, each mapped to
    "excluded" with a `_comment`. Caller (mode_init_system_paths) is
    responsible for NOT also emitting a generic per-directory rule for
    wp-admin/wp-includes (would collide on an identical-length prefix).
    """
    rules: list[dict] = []
    for d in WP_CORE_DIRS:
        rules.append(
            {
                "_comment": (
                    "WordPress core (auto-detected) — never a bare "
                    "'wp-' prefix, it would also swallow wp-content/"
                ),
                "prefix": d,
                "system": "excluded",
            }
        )
    for f in WP_CORE_ROOT_FILES:
        rules.append(
            {
                "_comment": "WordPress core root file (auto-detected)",
                "prefix": f,
                "system": "excluded",
            }
        )
    return rules
