#!/usr/bin/env bash
# security-guard-files.sh
# Event: PreToolUse
# Matcher: Write|Edit
# Scope: Universal — fires in both main session and sub-agents
#
# Intercepts file Write/Edit operations before execution. Blocks writes
# to sensitive files (keys, credentials, lock files) and warns on writes
# to configuration and governance files. Logs all blocks/warnings to vault.

set -uo pipefail

INPUT=$(cat)

# Extract file path from tool_input
FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
data = json.load(sys.stdin)
ti = data.get('tool_input', {})
print(ti.get('file_path', ''))
" 2>/dev/null || echo "")

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
VAULT_DIR="$PROJECT_DIR/.smith/vault"
CURRENT_SESSION_FILE="$VAULT_DIR/.current-session"
CONFIG_FILE="$PROJECT_DIR/.smith/security-config.json"

# Get just the filename for pattern matching
FILENAME=$(basename "$FILE_PATH")
FILENAME_LOWER=$(echo "$FILENAME" | tr '[:upper:]' '[:lower:]')

# Load security config
WARN_ONLY="false"
ALLOWED_FILES=""
if [ -f "$CONFIG_FILE" ]; then
    WARN_ONLY=$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(str(d.get('warn_only_mode', False)).lower())" 2>/dev/null || echo "false")
    ALLOWED_FILES=$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print('\n'.join(d.get('allowed_files', [])))" 2>/dev/null || echo "")
fi

# Helper: log to vault session log
log_security() {
    local action="$1" filepath="$2" pattern="$3" reason="$4"
    if [ -f "$CURRENT_SESSION_FILE" ]; then
        local session_file
        session_file=$(cat "$CURRENT_SESSION_FILE")
        if [ -f "$session_file" ]; then
            local now
            now=$(date -u +"%H:%M:%S")
            printf "\n### [%s] SECURITY: File write %s\n\n**File:** \`%s\`\n**Pattern matched:** %s\n**Reason:** %s\n" \
                "$now" "$action" "$filepath" "$pattern" "$reason" >> "$session_file"
        fi
    fi
}

# Helper: deny
deny() {
    local reason="$1" pattern="$2"
    log_security "blocked" "$FILE_PATH" "$pattern" "$reason"
    if [ "$WARN_ONLY" = "true" ]; then
        cat << EOJSON
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "additionalContext": "SMITH SECURITY WARNING (warn-only mode): $reason"
  }
}
EOJSON
        exit 0
    fi
    cat << EOJSON
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "SMITH SECURITY: $reason"
  }
}
EOJSON
    exit 2
}

# Helper: warn
warn() {
    local reason="$1" pattern="$2"
    log_security "warned" "$FILE_PATH" "$pattern" "$reason"
    cat << EOJSON
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "additionalContext": "SMITH SECURITY WARNING: $reason"
  }
}
EOJSON
    exit 0
}

# Check allowlist
if [ -n "$ALLOWED_FILES" ]; then
    while IFS= read -r allowed; do
        if [ -n "$allowed" ] && [ "$FILENAME" = "$allowed" ]; then
            exit 0
        fi
    done <<< "$ALLOWED_FILES"
fi

# ============================================================
# BLOCK: Private keys and certificates
# ============================================================

if echo "$FILENAME_LOWER" | grep -qE '\.(pem|key|p12|pfx|jks|keystore)$'; then
    deny "Blocked write to private key or certificate file '$FILENAME'. These files should be managed manually, not by AI." "Private key/certificate"
fi

if echo "$FILENAME_LOWER" | grep -qE '^id_rsa'; then
    deny "Blocked write to SSH private key '$FILENAME'. SSH keys must never be written by automated tools." "SSH private key"
fi

# ============================================================
# BLOCK: Cloud credentials
# ============================================================

if echo "$FILENAME_LOWER" | grep -qE '^credentials\.json$'; then
    deny "Blocked write to credentials.json. Cloud credential files should be managed manually." "Cloud credentials"
fi

if echo "$FILENAME_LOWER" | grep -qE '^service-account.*\.json$'; then
    deny "Blocked write to service account key file '$FILENAME'. These should be managed manually." "Service account key"
fi

# ============================================================
# BLOCK: Lock files (should be generated by package managers)
# ============================================================

if echo "$FILENAME_LOWER" | grep -qE '^(package-lock\.json|pnpm-lock\.yaml|poetry\.lock|yarn\.lock|Cargo\.lock)$'; then
    deny "Blocked direct write to lock file '$FILENAME'. Lock files should be generated by package managers (npm install, poetry lock, etc.), not written directly." "Lock file direct write"
fi

# ============================================================
# WARN: Environment files
# ============================================================

if echo "$FILENAME_LOWER" | grep -qE '^\.env(\..*)?$'; then
    warn "Writing to environment file '$FILENAME'. Verify this does not contain or expose secrets." "Environment file"
fi

# ============================================================
# WARN: Docker configuration
# ============================================================

if echo "$FILENAME_LOWER" | grep -qE '^(docker-compose\.(yml|yaml)|Dockerfile)$'; then
    warn "Writing to Docker configuration '$FILENAME'. Structural changes to container definitions should be reviewed carefully." "Docker configuration"
fi

# ============================================================
# WARN: Claude/Smith configuration
# ============================================================

if [ "$FILE_PATH" = "$PROJECT_DIR/.claude/settings.json" ]; then
    warn "Writing to .claude/settings.json. Changes to hook configuration affect all sessions. Review carefully." "Hook configuration"
fi

# ============================================================
# WARN: Governance documents
# ============================================================

if echo "$FILENAME_LOWER" | grep -qE '^constitution\.md$'; then
    warn "Writing to constitution.md. This is a governance document — changes should go through /smith-constitution for proper propagation." "Governance document"
fi

if echo "$FILE_PATH" | grep -qE 'CLAUDE\.md$'; then
    warn "Writing to CLAUDE.md. This configuration file affects all Claude Code sessions in this project." "Project configuration"
fi

# ============================================================
# No pattern matched — pass through
# ============================================================

exit 0
